- name: Setup Certificates
  hosts: raspberrypi
  remote_user: root
  vars:
    ca_dir : /usr/local/share/ca-certificates/local
    ca_key_path: "{{ ca_dir }}/local_ca.key"
    ca_cert_path: "{{ ca_dir }}/local_ca.crt"

  tasks:
    - name: Create CA cert direcotry
      ansible.builtin.file:
        path: "{{ ca_dir }}"
        state: directory
        mode: '0755'
    - name: Create CA private key
      community.crypto.openssl_privatekey:
        path: "{{ ca_key_path }}"
        state: present
    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ca_key_path }}"
        common_name: Raspberry Pi Local
        use_common_name_for_san: false
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr
    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ ca_cert_path }}"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "{{ ca_key_path }}"
        provider: selfsigned
    - name: Update CA Certificates
      ansible.builtin.shell: update-ca-certificates
