- name: Install Java
  hosts: raspberrypi
  remote_user: root
  vars:
    java_base: /opt/java
    corretto_url: "https://corretto.aws/downloads/latest/amazon-corretto-{}-aarch64-linux-jdk.tar.gz"

  tasks:
    - name: Create Java directory
      ansible.builtin.file:
        path: "{{ java_base }}"
        state: directory
        mode: '755'
    - name: Create Corretto17 directory
      ansible.builtin.file:
        path: "{{ java_base }}/corretto17"
        state: directory
        mode: '755'
    - name: Create Corretto21 directory
      ansible.builtin.file:
        path: "{{ java_base }}/corretto21"
        state: directory
        mode: '755'
    - import_tasks: download_tar_gz.yaml
      vars:
        url: "{{ corretto_url.format('17') }}"
        destination: "{{ java_base }}/corretto17"
        extra_opts: ['--strip-components=1', '--show-stored-names']
    - import_tasks: download_tar_gz.yaml
      vars:
        url: "{{ corretto_url.format('21') }}"
        destination: "{{ java_base }}/corretto21"
        extra_opts: ['--strip-components=1', '--show-stored-names']
    - name: Set permissions
      ansible.builtin.file:
        path: "{{ java_base }}"
        recurse: true
        mode: '755'
