- name: Install Keycloak
  hosts: raspberrypi
  remote_user: root
  vars:
    version: "24.0.3"
    download_url: "https://github.com/keycloak/keycloak/releases/download/{{ version }}/keycloak-{{ version }}.tar.gz"
    ca_dir : /usr/local/share/ca-certificates/local
    ca_key_path: "{{ ca_dir }}/local_ca.key"
    ca_cert_path: "{{ ca_dir }}/local_ca.crt"
    cert_dir: /home/keycloak/cert
    key_file: "{{ cert_dir }}/keycloak.key"
    cert_file: "{{ cert_dir }}/keycloak.crt"

  tasks:
    - import_tasks: service_user.yaml
      vars:
        user_name: keycloak
    - import_tasks: download_tar_gz.yaml
      vars:
        url: "{{ download_url }}" 
        destination: /home/keycloak
        extra_opts: ['--strip-components=1', '--show-stored-names']
    - name: Fix permissions
      ansible.builtin.file:
        path: /home/keycloak
        owner: keycloak
        group: keycloak
        recurse: true
        mode: '755'
    - import_tasks: certificate.yaml
      vars:
        domain: keycloak.local
    - name: Copy config file
      ansible.builtin.copy:
        src: keycloak.conf
        dest: /home/keycloak/conf/keycloak.conf
        owner: keycloak
        group: keycloak
        mode: '400'
    - import_tasks: systemd_service.yaml
      vars:
        name: keycloak
        user: keycloak
        group: keycloak
        exec: /home/keycloak/bin/kc.sh start
        environment_variables:
          JAVA_HOME: /opt/java/corretto17
