- name: Update Raspberry Pi
  hosts: raspberrypi
  remote_user: root
  vars:
    kubernetes_version: v1.29

  tasks:
    - name: Create /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/api/keyrings
        state: directory
        mode: '0755'
    - name: Setup Kubernetes Keys
      ansible.builtin.shell: curl -fsSL "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key" | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: Add Apt Kubernetes Repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/" /
        state: present
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: full
    - name: Install Packages
      ansible.builtin.apt:
        pkg:
          - zsh
          - vim
          - libnss3-tools
          - apt-transport-https
          - ca-certificates
          - curl
          - kubectl
    - name: Create sh link
      ansible.builtin.file:
        src: /usr/bin/bash
        state: link
        dest: /bin/sh
        follow: false
    - name: Check if mkcert installed
      ansible.builtin.stat:
        path: /usr/local/bin/mkcert
      ignore_errors: true
      register: mkcert_installed
    - name: Download mkcert
      ansible.builtin.command: wget -O /usr/local/bin/mkcert "https://dl.filippo.io/mkcert/latest?for=linux/arm64"
      when: not mkcert_installed.stat.exists
    - name: Make mkcert executable
      ansible.builtin.file:
        path: /usr/local/bin/mkcert 
        state: touch
        mode: u=rwx,g=rwx,o=rwx
      when: not mkcert_installed.stat.exists
    - name: Check if ORY CLI installed (Hydra/Kratos)
      ansible.builtin.stat:
        path: /usr/local/bin/ory
      ignore_errors: true
      register: ory_installed
    - name: Install ORY CLI (Hydra/Kratos)
      ansible.builtin.shell: bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b /usr/local/bin ory
      when: not ory_installed.stat.exists
    - name: Update ORY CLI permissions
      ansible.builtin.file:
        path: /usr/local/bin/ory
        state: touch
        mode: u=rwx,g=rx,o=rx
