- name: Update Raspberry Pi
  hosts: raspberrypi
  remote_user: root

  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: full
    - name: Install Packages
      ansible.builtin.apt:
        pkg:
          - zsh
          - vim
    - name: Create Operator user
      ansible.builtin.user:
        name: operator
        group: operator
        create_home: true
        shell: /usr/bin/zsh
        password: "{{ 'InitialPassword' | password_hash('sha512') }}"
        update_password: on_create
    - name: Create sh link
      ansible.builtin.file:
        src: /usr/bin/bash
        state: link
        dest: /bin/sh
        follow: false
    - name: Download Oh My Zsh
      ansible.builtin.command: wget -O /home/operator/install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      become: yes
      become_user: operator
    - name: Make Oh My Zsh installer runnable
      ansible.builtin.file:
        path: /home/operator/install.sh
        state: touch
        mode: u=rwx,g=r,o=r
      become: yes
      become_user: operator
    - name: Install Oh My Zsh
      ansible.builtin.command: /home/operator/install.sh --unattended --keep-zshrc
      become: yes
      become_user: operator
    - name: Delete Oh My Zsh Installer
      ansible.builtin.file:
        path: /home/operator/install.sh
        state: absent
      become: yes
      become_user: operator
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: .zshrc
        dest: /home/operator/.zshrc
        owner: operator
        group: operator
        mode: '0644'