- name: Manage Podman
  hosts: raspberrypi
  remote_user: root
  vars:
    etc_certs_dir: /etc/containers/certs.d
    cert_file_name: raspberrypi_local.crt
    key_file_name: raspberrypi_local.key
    cert_dir: /opt/certs/raspberrypi.local
    cert_file: "{{ cert_dir }}/{{ cert_file_name }}"
    key_file: "{{ cert_dir }}/{{ key_file_name }}"

  tasks:
    - name: Install Podman package
      ansible.builtin.apt:
        pkg:
          - podman
    - name: Link raspberrypi.local cert
      ansible.builtin.file:
        follow: false
        src: "{{ cert_file }}"
        dest: "{{ etc_certs_dir }}/{{ cert_file_name }}"
        state: link
        force: true
    - name: Link raspberrypi.local key
      ansible.builtin.file:
        follow: false
        src: "{{ key_file }}"
        dest: "{{ etc_certs_dir }}/{{ key_file_name }}"
        state: link
        force: true
    - name: Create Registry volume
      containers.podman.podman_volume:
        name: podman-registry-volume
        state: present
    - name: Create Registry container
      containers.podman.podman_container:
        name: podman-registry
        image: registry:2
        rm: true
        state: created
        ports:
          - "443:443"
        env:
          REGISTRY_HTTP_ADDR: 0.0.0.0:443
          REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/{{ cert_file_name }}"
          REGISTRY_HTTP_TLS_KEY: "/certs/{{ key_file_name }}"
        mounts:
          - "type=bind,src={{ cert_dir }},dst=/certs"
        volumes:
          - "podman-registry-volume:/var/lib/registry"
        generate_systemd:
          new: true
          names: true
          path: /etc/systemd/system
          restart_policy: always
          container_prefix: ""
          restart_sec: 20
    - name: Ensure registry container is started and enabled
      ansible.builtin.systemd:
        name: podman-registry
        daemon_reload: true
        state: started
        enabled: true
    - name: Copy registries.conf
      ansible.builtin.copy:
        src: registries.conf
        dest: /etc/containers/registries.conf
        owner: root
        group: root
        mode: '0644'