- name: Manage Podman
  hosts: raspberrypi
  remote_user: root
  vars:
    ca_dir : /usr/local/share/ca-certificates/local
    ca_key_path: "{{ ca_dir }}/local_ca.key"
    ca_cert_path: "{{ ca_dir }}/local_ca.crt"

    certs_dir: /etc/containers/certs.d
    cert_file_name: podman_local.crt
    key_file_name: podman_local.key
    cert_file: "{{ certs_dir }}/{{ cert_file_name }}"
    key_file: "{{ certs_dir }}/{{ key_file_name }}"

  tasks:
    - name: Create certificate private key
      community.crypto.openssl_privatekey:
        path: "{{ key_file }}"
        state: present
    - name: Change key permissions
      ansible.builtin.file:
        path: "{{ key_file }}"
        mode: '0744'
    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ key_file }}"
        common_name: podman.local
        organization_name: Raspberry Pi
        subject_alt_name:
          - "DNS:podman.local"
      register: csr
    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        force: true
        path: "{{ cert_file }}"
        csr_content: "{{ csr.csr }}"
        privatekey_path: "{{ key_file }}"
        provider: ownca
        ownca_path: "{{ ca_cert_path }}"
        ownca_privatekey_path: "{{ ca_key_path }}"
        ownca_not_after: +365d  # valid for one year
        ownca_not_before: "-1d"  # valid since yesterdaw

    - name: Add podman.local to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: 'podman.local'
        state: present
        line: 127.0.0.1 podman.local

    - name: Install Podman package
      ansible.builtin.apt:
        pkg:
          - podman
    - name: Create Registry volume
      containers.podman.podman_volume:
        name: podman-registry-volume
        state: present
    - name: Create Registry container
      containers.podman.podman_container:
        name: podman-registry
        image: registry:2
        rm: true
        state: created
        ports:
          - "443:443"
        env:
          REGISTRY_HTTP_ADDR: 0.0.0.0:443
          REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/{{ cert_file_name }}"
          REGISTRY_HTTP_TLS_KEY: "/certs/{{ key_file_name }}"
        mounts:
          - "type=bind,src={{ certs_dir }},dst=/certs"
        volumes:
          - "podman-registry-volume:/var/lib/registry"
        generate_systemd:
          new: true
          names: true
          path: /etc/systemd/system
          restart_policy: always
          container_prefix: ""
          restart_sec: 20
    - name: Ensure registry container is started and enabled
      ansible.builtin.systemd:
        name: podman-registry
        daemon_reload: true
        state: started
        enabled: true
    - name: Copy registries.conf
      ansible.builtin.copy:
        src: registries.conf
        dest: /etc/containers/registries.conf
        owner: root
        group: root
        mode: '0644'