- name: Manage Podman
  hosts: raspberrypi
  remote_user: root
  tasks:

    - name: Install Podman package
      ansible.builtin.apt:
        pkg:
          - podman
    - name: Create Registry volume
      containers.podman.podman_volume:
        name: podman-registry-volume
        state: present
    - name: Create Registry container
      containers.podman.podman_container:
        name: podman-registry
        image: registry:2
        rm: true
        state: created
        ports:
          - "443:443"
        env:
          REGISTRY_HTTP_ADDR: 0.0.0.0:443
          REGISTRY_HTTP_TLS_CERTIFICATE: /certs/raspberrypi_local.crt
          REGISTRY_HTTP_TLS_KEY: /certs/raspberrypi_local.key
        mounts:
          - "type=bind,src=/etc/containers/certs.d,dst=/certs"
        volumes:
          - "podman-registry-volume:/var/lib/registry"
        generate_systemd:
          new: true
          names: true
          path: /etc/systemd/system
          restart_policy: always
          container_prefix: ""
          restart_sec: 20
    - name: Ensure registry container is started and enabled
      ansible.builtin.systemd:
        name: podman-registry
        daemon_reload: true
        state: started
        enabled: true
    - name: Copy registries.conf
      ansible.builtin.copy:
        src: registries.conf
        dest: /etc/containers/registries.conf
        owner: root
        group: root
        mode: '0644'