- name: Install PostgreSQL
  hosts: raspberrypi
  remote_user: root
  vars:
    ca_dir : /usr/local/share/ca-certificates/local
    ca_key_path: "{{ ca_dir }}/local_ca.key"
    ca_cert_path: "{{ ca_dir }}/local_ca.crt"
    cert_dir: /home/postgres/cert
    key_file: "{{ cert_dir }}/postgres.key"
    cert_file: "{{ cert_dir }}/postgres.crt"

  tasks:
    - name: Create key directory
      ansible.builtin.file:
        path: /usr/share/postgresql-common/pgdg
        state: directory
        mode: '0755'
    - name: Setup Postgres Keys
      ansible.builtin.shell: curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - name: Add Apt Postgres Repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main
        state: present
    - name: Update repositories cache and install packages
      ansible.builtin.apt:
        pkg:
          - postgresql-16
          - python3-psycopg2 # to have community.postgresql.postgresql_db working
        update_cache: yes
    - import_tasks: service_user.yaml
      vars:
        user_name: postgres
    - import_tasks: certificate.yaml
      vars:
        domain: postgres.local
    - name: Copy config file
      ansible.builtin.template:
        src: postgres/postgresql.conf.tmpl
        dest: /var/lib/postgresql/16/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '400'
    - name: Copy pg_hba.conf
      ansible.builtin.copy:
        src: postgres/pg_hba.conf 
        dest: /etc/postgresql/16/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '400'
    - name: Fix permissions
      ansible.builtin.file:
        path: /var/lib/postgresql/16/main
        owner: postgres
        group: postgres
        recurse: true
        mode: '700'
    - name: Fix cert permissions
      ansible.builtin.file:
        path: /home/postgres/cert
        owner: postgres
        group: postgres
        recurse: true
        mode: '600'
    - name: "Start and enable Postgresql service"
      ansible.builtin.systemd_service:
        state: started
        name: postgresql
        enabled: true
        daemon_reload: true
    - name: Create a new database with name "demo"
      community.postgresql.postgresql_db:
        name: demo
        login_unix_socket: /var/run/postgresql
