- name: Copy systemd service file
  ansible.builtin.template:
    src: template.service
    dest: "/etc/systemd/system/{{ name }}.service"
    owner: root
    mode: "644"
- name: "Start and enable {{ name }} service"
  ansible.builtin.systemd_service:
    state: "{{ state | default('started') }}"
    name: "{{ name }}"
    enabled: true
    daemon_reload: true