serve:
  public:
    base_url: "{{ kratos_url }}:4433"
    tls:
      key:
        path: "{{ key_file }}"
      cert:
        path: "{{ cert_file }}"
  admin:
    base_url: "{{ kratos_url }}:4434"
    tls:
      key:
        path: "{{ key_file }}"
      cert:
        path: "{{ cert_file }}"
  
dsn: "{{ dsn }}"

selfservice:
  default_browser_return_url: "{{ kratos_url }}:4455/"
  allowed_return_urls:
    - "{{ kratos_url }}:4455"
  methods:
    password:
      enabled: true
    oidc:
      enabled: false
  flows:
    error:
      ui_url: "{{ kratos_url }}:4455/error"

    settings:
      ui_url: "{{ kratos_url }}:4455/settings"
      privileged_session_max_age: 15m
      required_aal: highest_available

    logout:
      after:
        default_browser_return_url: "{{ kratos_url }}:4455/login"

    login:
      ui_url: "{{ kratos_url }}:4455/login"

    registration:
      ui_url: "{{ kratos_url }}:4455/registration"
      after:
        password:
          hooks:
            - hook: session
log:
  level: debug
  format: text

oauth2_provider:
  url: "{{ hydra_url }}"

identity:
  default_schema_id: default
  schemas: 
    - id: default
      url: "file://{{ schema_file }}"

secrets:
  cookie:
    - "{{ lookup('community.general.random_string', length=32, special=false) }}"
  cipher:
    - "{{ lookup('community.general.random_string', length=32, special=false) }}"

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true